### ISSUE TITLE
Problems building with default firmware sketch

### ISSUE THREAD

**Issue by noseglasses** [cdisselkoen/Kaleidoscope-Hardware-Virtual#3]
Before I can build the HV plugin with the stock firmware sketch from Arduino-Boards, I always have to uncomment things related to the Kaleidoscope-Numlock and Kaleidoscope-Model01-TestMode in the stock sketch due to build errors.

This might be valuable information for other users that want to try out the HV plugin. Could this possibly be added to the README.md. Unless, of course, there is any other possible workaround that would enable to build without the required modifications described.

**Comment by cdisselkoen** [comment]
Interesting.  Model01-TestMode is known to not build under Hardware-Virtual (see keyboardio/Kaleidoscope-Model01-TestMode#3), but I haven't had problems with Numlock, and it builds fine in my current setup.  I'll keep investigating, but do you have an idea for how I might reproduce Numlock build problems?

It's a good suggestion to put warnings in the README for affected plugins until these issues are resolved - I'll do that soon.

**Comment by cdisselkoen** [comment]
A fix for some Kaleidoscope-Numlock problems is in keyboardio/Kaleidoscope-Hardware-Virtual#12.  I'm not sure if that's the original issue here, but Numlock builds and tests fine for me under Hardware-Virtual after that PR.  If things are still not fixed, feel free to file another issue on the other repo.  Closing this here in favor of discussions on the other repo.
